#!/bin/sh
# Extracts constants from glext.h and outputs a Go map literal

echo "package glcaps

// glconstants is generated by \`./scripts/gl-trim.sh > glconst.go\`
var glconstants = map[string]uint32 {"

cat scripts/glcorearb.h scripts/glext.h | grep -E "^#define GL_[A-Z0-9_]+[[:space:]]*0x[A-F0-9]+\$" | sort -u | while read -r line
do
    left=`echo $line | cut -d " " -f2`
    right=`echo $line | cut -d " " -f3`
    echo "\"$left\": $right,"
done

echo "}"

