/*
Package xff implements a decoder for the DirectX (.x) file format in
Go (Golang).

THIS IS A PREVIEW RELEASE. A few templates are missing and the returned data
is not decoded from bytes to types properly. The testdata is missing. It needs
a refactor. This will be fixed early next week (beginning Feb 24th 2020).

This parser is (or aims to be) a complete implementation. It supports user-defined
templates and should be able to parse *every* well-formed DirectX (.x) file.

There are a few features not yet implemented - not because they are difficult
to implement, but because I can't find any real-world examples using that
feature to test against. Things like object referencing by UIID instead of
name, or the binary encoded DirectX .x file format, arrays of strings, or
multidimensional arrays. If you find something that doesn't work (and should)
then send in a sample and it'll get fixed quickly!

This is free and open source software. It took six days to write
the first production-ready version - so if you find this module useful enough
that you end up using it in a commercial product then there is a polite
expectation of a donation to the author. The suggested donation is a sum equal
to the retail cost of a single copy of your product. To do so, make a payment at
https://www.paypal.me/TawesoftLtd and forward a copy of your receipt to
"xff-thanks@tawesoft.co.uk". Alternatively you can purchase commercial support
through open-source@tawesoft.co.uk. This is, of course, entirely optional.

DirectX is a registered trademark of Microsoft Corporation in the United States
and/or other countries.

For license information, documentation, source code, support, links, etc. please see
https://tawesoft.co.uk/go/xff

This module is part of https://tawesoft.co.uk/go
*/
package xff // import "tawesoft.co.uk/go/xff"

// SPDX-License-Identifier: MIT

// Code generated by (tawesoft.co.uk/go/) fluff.py: DO NOT EDIT.