/*
Package xff implements a decoder for the DirectX (.x) file format in
Go (Golang).

THIS IS A PREVIEW RELEASE. A few templates are missing and the returned data
is not decoded from bytes to types properly. The testdata is missing. It needs
a refactor. This will be fixed early next week (beginning Feb 24th 2020).

This parser is (or aims to be) a complete implementation that supports
user-defined templates. It should be able to parse *every* well-formed DirectX
(.x) file. Get in touch if you find any that don't parse correctly.

This is free and open source software. If you find this module useful enough
that you use it in a commercial product, it is suggested that you donate a
sum to the author equal to the cost of one copy of your product. To do so,
make a donation at https://www.paypal.me/TawesoftLtd and forward a copy of your
receipt to "ben+xff-donation@tawesoft.co.uk". Alternatively you can purchase
commercial support through open-source@tawesoft.co.uk. This is, of course,
entirely optional.

DirectX is a registered trademark of Microsoft Corporation in the United States
and/or other countries.

For license information, documentation, source code, support, links, etc. please see
https://tawesoft.co.uk/go/xff

This module is part of https://tawesoft.co.uk/go
*/
package xff // import "tawesoft.co.uk/go/xff"

// SPDX-License-Identifier: MIT

// Code generated by (tawesoft.co.uk/go/) fluff.py: DO NOT EDIT.