// tawesoft.co.uk/go/glcaps
// 
// Copyright © 2020 Tawesoft Ltd <open-source@tawesoft.co.uk>
// Copyright © 2020 Ben Golightly <ben@tawesoft.co.uk>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction,  including without limitation the rights
// to use,  copy, modify,  merge,  publish, distribute, sublicense,  and/or sell
// copies  of  the  Software,  and  to  permit persons  to whom  the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED  "AS IS",  WITHOUT WARRANTY OF ANY KIND,  EXPRESS OR
// IMPLIED,  INCLUDING  BUT  NOT LIMITED TO THE WARRANTIES  OF  MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE  AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
// AUTHORS  OR COPYRIGHT HOLDERS  BE LIABLE  FOR ANY  CLAIM,  DAMAGES  OR  OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Package glcaps provides a nice interface to declare OpenGL capabilities you
// care about, including minimum required extensions or capabilities. Glcaps has
// no dependencies and is agnostic to the exact OpenGL binding used.
// 
// OpenGL® and the oval logo are trademarks or registered trademarks of Hewlett
// Packard Enterprise in the United States and/or other countries worldwide.
// 
// Examples
// 
// Example using glcaps with an OpenGL binding and a struct with tags.
// 
// See https://godoc.org/tawesoft.co.uk/go/glcaps#Parse for a description of the
// struct annotation syntax.
//
// https://www.tawesoft.co.uk/go/doc/glcaps/examples/example/
//
//
// Package Information
//
// License: MIT (see LICENSE.txt)
//
// Stable: yes
//
// For more information, documentation, source code, examples, support, links,
// etc. please see https://www.tawesoft.co.uk/go and 
// https://www.tawesoft.co.uk/go/glcaps
package glcaps // import "tawesoft.co.uk/go/glcaps"

// Code generated by internal. DO NOT EDIT.
// Instead, edit DESC.txt and run mkdocs.sh.