/*
Package glcaps provides a nice interface to declare OpenGL capabilities you care about, including minimum required
extensions or capabilities. Glcaps has no dependencies and is agnostic to the exact OpenGL binding used.

OpenGL® and the oval logo are trademarks or registered trademarks of Hewlett Packard Enterprise in
the United States and/or other countries worldwide.

For license information, documentation, source code, support, links, etc. please see
https://tawesoft.co.uk/go/glcaps

This module is part of https://tawesoft.co.uk/go
*/
package glcaps // import "tawesoft.co.uk/go/glcaps"

// SPDX-License-Identifier: MIT

// Code generated by (tawesoft.co.uk/go/) fluff.py: DO NOT EDIT.