// tawesoft.co.uk/go/log
// 
// Copyright © 2021 Ben Golightly <ben@tawesoft.co.uk>
// Copyright © 2021 Tawesoft Ltd <opensource@tawesoft.co.uk>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction,  including without limitation the rights
// to use,  copy, modify,  merge,  publish, distribute, sublicense,  and/or sell
// copies  of  the  Software,  and  to  permit persons  to whom  the Software is
// furnished to do so.
// 
// THE SOFTWARE IS PROVIDED  "AS IS",  WITHOUT WARRANTY OF ANY KIND,  EXPRESS OR
// IMPLIED,  INCLUDING  BUT  NOT LIMITED TO THE WARRANTIES  OF  MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE  AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
// AUTHORS  OR COPYRIGHT HOLDERS  BE LIABLE  FOR ANY  CLAIM,  DAMAGES  OR  OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Package log provides a common way to quickly configure a logging implementation
// with file rotation, syslog, console output, etc. for some popular logging
// implementations such as zerolog.
// 
// This package defines the configuration interface, which is json-encodable.
// 
// Loggers are concretely implemented by the packages in the subfolder e.g.
// tawesoft.co.uk/go/log/zerolog.
// 
// The package also wraps the stdlib syslog as an interface without it being a
// compile-time constraint so that it can be imported on platforms that don't
// support syslog (like Windows), giving a runtime error if used instead.
// 
// Examples
// 
// 
//
// https://www.tawesoft.co.uk/go/doc/log/examples/encode/
//
//
// Package Information
//
// License: MIT-0 (see LICENSE.txt)
//
// Stable: candidate
//
// For more information, documentation, source code, examples, support, links,
// etc. please see https://www.tawesoft.co.uk/go and 
// https://www.tawesoft.co.uk/go/log
package log // import "tawesoft.co.uk/go/log"

// Code generated by internal. DO NOT EDIT.
// Instead, edit DESC.txt and run mkdocs.sh.