/*
Package humanize implements lightweight human-readable numbers for Go.

Why use this package?

Compare tawesoft/go/humanize vs dustin/go-humanize: Tawesoft's parses input about 5 times faster with fewer memory
allocations, and formats output about 25% quicker than dustin's. But dustin's is so far more complete, older, has a
stable API, and has been tested by more people.

For license information, documentation, source code, support, links, etc. please see
https://tawesoft.co.uk/go/humanize

This module is part of https://tawesoft.co.uk/go
*/
package humanize // import "tawesoft.co.uk/go/humanize"

// SPDX-License-Identifier: MIT-0

// Code generated by (tawesoft.co.uk/go/) fluff.py: DO NOT EDIT.