/*
Package dialog implements simple cross platform native MessageBox/Alert dialogs for Go.

Currently only Windows and Linux targets are supported.

On Linux, uses (in order of preference) `zenity`, `xmessage`, or stdio.

Example:

    package main
    
    import "tawesoft.co.uk/go/dialog"
    
    func main() {
        dialog.Alert("Message")
        dialog.Alert("There are %d lights", 4)
    }

For license information, documentation, source code, support, links, etc. please see
https://tawesoft.co.uk/go/dialog

This module is part of https://tawesoft.co.uk/go
*/
package dialog // import "tawesoft.co.uk/go/dialog"

// SPDX-License-Identifier: MIT-0

// Code generated by (tawesoft.co.uk/go/) fluff.py: DO NOT EDIT.