// tawesoft.co.uk/go/drop
// 
// Copyright © 2020 - 2021 Tawesoft Ltd <open-source@tawesoft.co.uk>
// Copyright © 2020 - 2021 Ben Golightly <ben@tawesoft.co.uk>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction,  including without limitation the rights
// to use,  copy, modify,  merge,  publish, distribute, sublicense,  and/or sell
// copies  of  the  Software,  and  to  permit persons  to whom  the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED  "AS IS",  WITHOUT WARRANTY OF ANY KIND,  EXPRESS OR
// IMPLIED,  INCLUDING  BUT  NOT LIMITED TO THE WARRANTIES  OF  MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE  AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
// AUTHORS  OR COPYRIGHT HOLDERS  BE LIABLE  FOR ANY  CLAIM,  DAMAGES  OR  OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Package drop implements the ability to start a process as root, open
// privileged resources as files, drop privileges to become a given user account,
// and inherit file handles across the dropping of privileges.
// 
// NOTE: This package has only been tested on Linux. YMMV.
// 
// NOTE: This package WILL NOT WORK on Windows.
// 
// WARNING: if a process opens a config file as root, that file must be writable
// by root or system accounts only. The safest way to do this is change it to
// be root-owned with permissions 0644 (or 0600).
// 
// Examples
// 
// Opens privileged files and ports as root, then drops privileges
//
// https://www.tawesoft.co.uk/go/doc/drop/examples/drop/
//
//
// Package Information
//
// License: MIT (see LICENSE.txt)
//
// Stable: candidate
//
// For more information, documentation, source code, examples, support, links,
// etc. please see https://www.tawesoft.co.uk/go and 
// https://www.tawesoft.co.uk/go/drop
//
//     2021-07-09
//     
//         * The Inheritable interface has changed. It now has a Close() method. The
//           Name() method has also been renamed String() to satisfy the stringer
//           interface.
//     
//         * The Drop() function now returns an extra value before the error value.
//           This `closer` can be used by the child process to close all Inheritable
//           handles. Alternatively, it is possible to ignore this and close each
//           handle by calling their Close() method.
//     
//         * The package now exports the builtins InheritableFile and
//           InheritableNetListener that implement the Inheritable interface for
//           Files and net.Listeners. These are created by the functions
//           NewInheritableFile, NewInheritableTCPListener and
//           NewInheritableUnixListener.
//     
//         * Drop() no longer panics on non-Linux platforms. However, it has only been
//           tested on Linux so YMMV. It will continue to panic on Windows. Listeners
//           also cannot be inherited on the JS platform target as they are not backed
//           by files.
//     
//     2021-03-17
//     
//         * Drop() now returns a (bool, error) 2-tuple. The first return value,
//           if true, indicates that the caller should immediately exit.
//     
//     2020-11-27
//     
//         * Drop() functionality has been moved to tawesoft.co.uk/go/drop with
//           changes to Inheritables from a struct to an interface.
//     
package drop // import "tawesoft.co.uk/go/drop"

// Code generated by internal. DO NOT EDIT.
// Instead, edit DESC.txt and run mkdocs.sh.