// tawesoft.co.uk/go/sqlp
// 
// Copyright © 2020 Tawesoft Ltd <open-source@tawesoft.co.uk>
// Copyright © 2020 Ben Golightly <ben@tawesoft.co.uk>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction,  including without limitation the rights
// to use,  copy, modify,  merge,  publish, distribute, sublicense,  and/or sell
// copies  of  the  Software,  and  to  permit persons  to whom  the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED  "AS IS",  WITHOUT WARRANTY OF ANY KIND,  EXPRESS OR
// IMPLIED,  INCLUDING  BUT  NOT LIMITED TO THE WARRANTIES  OF  MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE  AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
// AUTHORS  OR COPYRIGHT HOLDERS  BE LIABLE  FOR ANY  CLAIM,  DAMAGES  OR  OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 

// Package sqlp ("SQL-plus" or "squelp!") defines helpful interfaces and
// implements extra features for Go SQL database drivers. Specific driver
// extras are implemented in the subdirectories.
// 
// Features
// 
// * Open a SQLite database with foreign keys, UTF8 collation, etc. made easy
// to avoid copy+pasting the same boilerplate into each project.
// 
// * "Missing" essentials like escaping an SQL column name
// (https://github.com/golang/go/issues/18478) or examining an SQL error for
// properties such as IsUniqueConstraintError when inserting duplicate items
// 
// * Interfaces like Queryable which is implemented by all of sql.DB, sql.Tx
// and sql.Stmt, for performing queries regardless of if they are in a
// transaction or not.
// 
// Driver extras
// 
// * tawesoft.co.uk/go/sqlp/sqlite3 (mattn/go-sqlite3)
//
// Package Information
//
// License: MIT (see LICENSE.txt)
//
// Stable: candidate
//
// For more information, documentation, source code, examples, support, links,
// etc. please see https://www.tawesoft.co.uk/go and 
// https://www.tawesoft.co.uk/go/sqlp
package sqlp // import "tawesoft.co.uk/go/sqlp"

// Code generated by internal. DO NOT EDIT.
// Instead, edit DESC.txt and run mkdocs.sh.