// tawoesoft.co.uk/go/operator
// 
// Copyright © 2020 Tawesoft Ltd <open-source@tawesoft.co.uk>
// Copyright © 2020 Ben Golightly <ben@tawesoft.co.uk>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction,  including without limitation the rights
// to use,  copy, modify,  merge,  publish, distribute, sublicense,  and/or sell
// copies  of  the  Software,  and  to  permit persons  to whom  the Software is
// furnished to do so.
// 
// THE SOFTWARE IS PROVIDED  "AS IS",  WITHOUT WARRANTY OF ANY KIND,  EXPRESS OR
// IMPLIED,  INCLUDING  BUT  NOT LIMITED TO THE WARRANTIES  OF  MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE  AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
// AUTHORS  OR COPYRIGHT HOLDERS  BE LIABLE  FOR ANY  CLAIM,  DAMAGES  OR  OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Package operator implements logical, arithmetic, bitwise and comparison
// operators as functions (like the Python operator module). Includes unary,
// binary, and n-ary functions with overflow checked variants.
// 
// Examples
// 
// Using operators as function arguments
//
// https://www.tawesoft.co.uk/go/doc/operator/examples/simple/
//
// Using operators in lookup tables for a command-line calculator program
//
// https://www.tawesoft.co.uk/go/doc/operator/examples/calculator/
//
//
// FROZEN - PLEASE MIGRATE
//
// These packages are moving to https://github.com/tawesoft/golib.
//
// This is to increase security against possible supply chain attacks such as
// our domain name expiring in the future and being registered by someone else.
//
// Please migrate to https://github.com/tawesoft/golib (when available) instead.
//
// Most programs relying on a package in this monorepo, such as the dialog or
// lxstrconv packages, will continue to work for the foreseeable future.
//
// Rarely used packages have been hidden for now - they are in the git commit
// history at https://github.com/tawesoft/go if you need to resurrect one.
//
//
// Package Information
//
// License: MIT-0 (see LICENSE.txt)
//
// Stable: yes
//
// For more information, documentation, source code, examples, support, links,
// etc. please see https://www.tawesoft.co.uk/go and 
// https://www.tawesoft.co.uk/go/operator
package operator // import "tawesoft.co.uk/go/operator"

// Code generated by internal. DO NOT EDIT.
// Instead, edit DESC.txt and run mkdocs.sh.