// tawesoft.co.uk/go/log/zero
// 
// Copyright © 2021 Ben Golightly <ben@tawesoft.co.uk>
// Copyright © 2021 Tawesoft Ltd <opensource@tawesoft.co.uk>
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction,  including without limitation the rights
// to use,  copy, modify,  merge,  publish, distribute, sublicense,  and/or sell
// copies  of  the  Software,  and  to  permit persons  to whom  the Software is
// furnished to do so.
// 
// THE SOFTWARE IS PROVIDED  "AS IS",  WITHOUT WARRANTY OF ANY KIND,  EXPRESS OR
// IMPLIED,  INCLUDING  BUT  NOT LIMITED TO THE WARRANTIES  OF  MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE  AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
// AUTHORS  OR COPYRIGHT HOLDERS  BE LIABLE  FOR ANY  CLAIM,  DAMAGES  OR  OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// Package log/zerolog makes it trivial to configure a zerolog logger with syslog,
// rotating file, and/or console output using the same uniform configuration
// interface.
// 
// See https://github.com/rs/zerolog
// 
// Log rotation provided by https://gopkg.in/natefinch/lumberjack.v2/
// 
// See https://www.tawesoft.co.uk/go/doc/log
// 
// Examples
// 
// 
//
// https://www.tawesoft.co.uk/go/doc/log/zerolog/examples/hello-world/
//
//
// Package Information
//
// License: MIT-0 (see LICENSE.txt)
//
// Stable: candidate
//
// For more information, documentation, source code, examples, support, links,
// etc. please see https://www.tawesoft.co.uk/go and 
// https://www.tawesoft.co.uk/go/log/zerolog
package zerolog // import "tawesoft.co.uk/go/log/zerolog"

// Code generated by internal. DO NOT EDIT.
// Instead, edit DESC.txt and run mkdocs.sh.